url: "https://modorg.pl" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/diversityhub-puap/" # the subpath of your site, e.g. /blog
title: "Puap - Bezpłatne szkolenia, doradztwo i narzędzia dla firm"

# Build settings
sass:
  sass_dir: _css
  style: compressed
